// Referral Service
// Handles referral codes and relationships from the database
import { supabase } from './supabase';

export interface ReferralCodeValidation {
  isValid: boolean;
  error?: string;
  userId?: string;
}

/**
 * Validates a referral code by checking if it exists in the database
 */
export async function validateReferralCode(code: string): Promise<ReferralCodeValidation> {
  try {
    if (!code || code.trim().length === 0) {
      return {
        isValid: false,
        error: 'Referral code cannot be empty',
      };
    }

    // Use the database function to validate
    const { data, error } = await supabase.rpc('validate_referral_code', {
      p_code: code.trim().toUpperCase(),
    });

    if (error) {
      console.error('Error validating referral code:', error);
      return {
        isValid: false,
        error: 'An error occurred while validating the referral code',
      };
    }

    if (data && data.length > 0) {
      const result = data[0];
      return {
        isValid: result.is_valid,
        error: result.error_message || undefined,
        userId: result.user_id || undefined,
      };
    }

    return {
      isValid: false,
      error: 'Invalid referral code',
    };
  } catch (error: any) {
    console.error('Exception validating referral code:', error);
    return {
      isValid: false,
      error: 'An error occurred while validating the referral code',
    };
  }
}

/**
 * Creates a referral relationship between referrer and referred user
 */
export async function createReferralRelationship(
  referrerUserId: string,
  referredUserId: string,
  referralCode: string,
  rewardAmount: number = 200 // Default reward amount in NGN
): Promise<{ error: any }> {
  try {
    // Use the database function to create referral
    const { error } = await supabase.rpc('create_referral', {
      p_referrer_user_id: referrerUserId,
      p_referred_user_id: referredUserId,
      p_referral_code: referralCode.trim().toUpperCase(),
      p_reward_amount: rewardAmount,
      p_reward_currency: 'NGN',
    });

    if (error) {
      console.error('Error creating referral relationship:', error);
      return { error };
    }

    return { error: null };
  } catch (error: any) {
    console.error('Exception creating referral relationship:', error);
    return { error };
  }
}

/**
 * Gets the referral code for a user (from user_profiles table)
 */
export async function getUserReferralCode(userId: string): Promise<{ code: string | null; error: any }> {
  try {
    const { data, error } = await supabase
      .from('user_profiles')
      .select('referral_code')
      .eq('user_id', userId)
      .single();

    if (error) {
      // If no record found, it's not necessarily an error
      if (error.code === 'PGRST116') {
        return { code: null, error: null };
      }
      console.error('Error fetching referral code:', error);
      return { code: null, error };
    }

    return { code: data?.referral_code || null, error: null };
  } catch (error: any) {
    console.error('Exception fetching referral code:', error);
    return { code: null, error };
  }
}

/**
 * Gets referral code as a simple string (for backward compatibility)
 */
export async function getUserReferralCodeString(userId: string): Promise<string | null> {
  const { code, error } = await getUserReferralCode(userId);
  if (error) {
    return null;
  }
  return code;
}

/**
 * Generates a referral code for a user
 * Note: Referral codes are automatically generated by the database trigger
 * This function ensures the profile exists and has a referral code
 */
export async function generateReferralCode(userId: string): Promise<{ code: string | null; error: any }> {
  try {
    // First, check if user already has a referral code
    const { code: existingCode, error: fetchError } = await getUserReferralCode(userId);
    
    if (existingCode) {
      return { code: existingCode, error: null };
    }

    // If no code exists, check if profile exists
    const { data: profile, error: profileError } = await supabase
      .from('user_profiles')
      .select('id, user_id, referral_code')
      .eq('user_id', userId)
      .single();

    // If profile doesn't exist, try to create it with a referral code
    if (profileError && profileError.code === 'PGRST116') {
      console.log('Profile not found, attempting to create profile with referral code...');
      
      // Generate a referral code from user ID
      const referralCodeValue = userId.replace(/-/g, '').substring(0, 7).toUpperCase();
      
      // Try to insert profile with referral code
      const { data: newProfile, error: insertError } = await supabase
        .from('user_profiles')
        .insert({
          user_id: userId,
          referral_code: referralCodeValue,
        })
        .select('referral_code')
        .single();

      if (insertError) {
        console.error('Error creating profile:', insertError);
        // If insert fails due to RLS, try using RPC function
        // For now, return error with helpful message
        return { 
          code: null, 
          error: {
            message: 'Unable to create user profile. Please contact support or try signing out and back in.',
            code: insertError.code,
            details: insertError.message,
          }
        };
      }

      if (newProfile?.referral_code) {
        return { code: newProfile.referral_code, error: null };
      }
    }

    // If profile exists but no referral code, try to update it
    if (profile && !profile.referral_code) {
      console.log('Profile exists but no referral code, generating one...');
      
      // Generate a referral code from user ID
      const referralCodeValue = userId.replace(/-/g, '').substring(0, 7).toUpperCase();
      
      const { data: updatedProfile, error: updateError } = await supabase
        .from('user_profiles')
        .update({ referral_code: referralCodeValue })
        .eq('user_id', userId)
        .select('referral_code')
        .single();

      if (updateError) {
        console.error('Error updating profile with referral code:', updateError);
        return { 
          code: null, 
          error: {
            message: 'Unable to generate referral code. Please contact support.',
            code: updateError.code,
            details: updateError.message,
          }
        };
      }

      if (updatedProfile?.referral_code) {
        return { code: updatedProfile.referral_code, error: null };
      }
    }

    // Wait a moment and try fetching again (in case trigger is still processing)
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const { code: retryCode, error: retryError } = await getUserReferralCode(userId);
    
    if (retryCode) {
      return { code: retryCode, error: null };
    }

    // If still no code, return helpful error
    return { 
      code: null, 
      error: retryError || fetchError || {
        message: 'Referral code not found. Please ensure your profile is set up correctly. If the issue persists, try signing out and back in.',
      }
    };
  } catch (error: any) {
    console.error('Exception generating referral code:', error);
    return { 
      code: null, 
      error: {
        message: error.message || 'An unexpected error occurred while generating referral code',
        details: error,
      }
    };
  }
}

/**
 * Gets referral statistics for a user
 */
export async function getReferralStats(userId: string): Promise<{
  totalReferrals: number;
  totalEarnings: number;
  pendingReferrals?: number;
  paidReferrals?: number;
  pendingEarnings?: number;
  paidEarnings?: number;
  error: any;
}> {
  try {
    // Use the database function to get stats
    const { data, error } = await supabase.rpc('get_referral_stats', {
      p_user_id: userId,
    });

    if (error) {
      console.error('Error fetching referral stats:', error);
      return { totalReferrals: 0, totalEarnings: 0, error };
    }

    if (data && data.length > 0) {
      const stats = data[0];
      return {
        totalReferrals: Number(stats.total_referrals) || 0,
        totalEarnings: Number(stats.total_earnings) || 0,
        pendingReferrals: Number(stats.pending_referrals) || 0,
        paidReferrals: Number(stats.paid_referrals) || 0,
        pendingEarnings: Number(stats.pending_earnings) || 0,
        paidEarnings: Number(stats.paid_earnings) || 0,
        error: null,
      };
    }

    return { totalReferrals: 0, totalEarnings: 0, error: null };
  } catch (error: any) {
    console.error('Exception fetching referral stats:', error);
    return { totalReferrals: 0, totalEarnings: 0, error };
  }
}

/**
 * Gets recent referrals for a user
 */
export async function getRecentReferrals(
  userId: string,
  limit: number = 10
): Promise<{
  referrals: Array<{
    id: string;
    referred_user_id: string;
    referral_code: string;
    reward_amount: number;
    reward_status: string;
    created_at: string;
  }>;
  error: any;
}> {
  try {
    // Use the database function to get recent referrals
    const { data, error } = await supabase.rpc('get_recent_referrals', {
      p_user_id: userId,
      p_limit: limit,
    });

    if (error) {
      console.error('Error fetching recent referrals:', error);
      return { referrals: [], error };
    }

    if (data) {
      const referrals = data.map((ref: any) => ({
        id: ref.id,
        referred_user_id: ref.referred_user_id,
        referral_code: ref.referral_code,
        reward_amount: Number(ref.reward_amount) || 0,
        reward_status: ref.reward_status,
        created_at: ref.created_at,
      }));

      return { referrals, error: null };
    }

    return { referrals: [], error: null };
  } catch (error: any) {
    console.error('Exception fetching recent referrals:', error);
    return { referrals: [], error };
  }
}

